### ISSUE TITLE
Trying to get AIRL example to work 

### ISSUE THREAD

**Issue by Maathuis** [nosyndicate/pytorchrl#5]
Hey. 

I am trying to get the framework to work, however I fail compile most of the code. 

Can you provide some install instructions? 

Thank you!

**Comment by nosyndicate** [comment]
sorry for the confusion. try install conda, then do `conda env create -f environment.yaml`. you need to first collect the samples than start training. I will commit the data_collect script later, sorry for that.

**Comment by Maathuis** [comment]
I managed to setup the environment. I was unfamiliar with conda environments, but it works wonderfully. 

Thank you for your response and I will wait on the data collection script :)

**Comment by nosyndicate** [comment]
Added the data collect script.

**Comment by YantianZha** [comment]
Where is the data collect script? Thanks.
